name: 🌿 Fern Scribe Documentation Request
description: Request AI-powered documentation updates using Fern Scribe
title: "[FERN-SCRIBE] "
labels: ["fern-scribe", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Fern Scribe AI Documentation Assistant
        
        Use this template to request AI-powered documentation updates. Fern Scribe will analyze your request and automatically generate file updates.

  - type: textarea
    id: request_description
    attributes:
      label: "📝 What do you want Fern Scribe (AI Technical Writer) to do?"
      description: "Example: Update the authentication guide to include new OAuth 2.0 flow, add examples for the new webhook endpoints"
      placeholder: "Describe docs changes here..."
    validations:
      required: true

  - type: input
    id: slack_thread
    attributes:
      label: "🔗 Link to existing Slack thread"
      description: "Ex. https://your-workspace.slack.com/archives/..."
      placeholder: "Paste slack link here..."

  - type: textarea
    id: existing_instructions
    attributes:
      label: "📋 Do you know of any documentation that needs to be updated?"
      description: "Ex. See buildwithfern.com/learn/docs/guides/authentication for current approach"
      placeholder: "Paste docs links here..."

  - type: textarea
    id: why_not_work
    attributes:
      label: "❌ If yes, describe why that documentation is incorrect"
      description: "Ex. Current docs don't cover the new OAuth scopes introduced in v2.1"
      placeholder: "Describe here..."

  - type: checkboxes
    id: changelog_required
    attributes:
      label: "📰 Changelog Update Required"
      description: "Should this change be included in the changelog?"
      options:
        - label: "Yes, include changelog entry"
        - label: "No changelog needed"

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context"
      description: "Any other relevant information, links, or requirements"
      placeholder: "Add info here..."