name: 🌿 Fern Scribe Documentation Request
description: Request AI-powered documentation updates using Fern Scribe
title: "[FERN-SCRIBE] "
labels: ["fern-scribe", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Fern Scribe AI Documentation Assistant
        
        Use this template to request AI-powered documentation updates. Fern Scribe will analyze your request and automatically generate file updates.

  - type: textarea
    id: request_description
    attributes:
      label: "📝 What do you want Fern Scribe (AI Technical Writer) to do?"
      description: "Describe the documentation changes you need"
      placeholder: "Example: Update the authentication guide to include new OAuth 2.0 flow, add examples for the new webhook endpoints"
    validations:
      required: true

  - type: input
    id: slack_thread
    attributes:
      label: "🔗 Link to existing Slack thread"
      description: "Optional: Link to relevant Slack discussion"
      placeholder: "https://your-workspace.slack.com/archives/..."

  - type: textarea
    id: existing_instructions
    attributes:
      label: "📋 Are there existing instructions in that docs for this issue?"
      description: "Reference any existing documentation or guidelines"
      placeholder: "See docs/guides/authentication.md for current approach"

  - type: textarea
    id: why_not_work
    attributes:
      label: "❌ If yes, describe why they didn't work"
      description: "Explain what's missing or incorrect in current docs"
      placeholder: "Current docs don't cover the new OAuth scopes introduced in v2.1"

  - type: checkboxes
    id: changelog_required
    attributes:
      label: "📰 Changelog Update Required"
      description: "Should this change be included in the changelog?"
      options:
        - label: "Yes, include changelog entry"
        - label: "No changelog needed"

  - type: dropdown
    id: priority
    attributes:
      label: "🚨 Priority Level"
      options:
        - "Low - Documentation enhancement"
        - "Medium - Important update needed"
        - "High - Critical documentation gap"
        - "Urgent - Blocks user adoption"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context"
      description: "Any other relevant information, links, or requirements"
      placeholder: "Related API changes, user feedback, etc."