navigation:
  - page: Overview
    path: ./pages/overview.mdx
  - page: Authentication
    path: ./pages/auth.mdx
  - page: Servers
    path: ./pages/servers.mdx            
  - section: Endpoints
    slug: endpoints
    contents:
      - page: HTTP JSON Endpoints
        path: ./pages/endpoints/rest.mdx
        slug: http
      - page: Multipart Form Uploads
        path: ./pages/endpoints/multipart.mdx
        slug: multipart
      - page: Server-Sent Events
        path: ./pages/endpoints/sse.mdx
        slug: sse
  - page: Webhooks
    path: ./pages/webhooks.mdx
  - page: Audiences
    path: ./pages/extensions/audiences.mdx
    slug: audiences
  - section: Extensions
    slug: extensions
    contents:
      - page: SDK Method Names
        path: ./pages/extensions/method-names.mdx
        slug: method-names
      - page: Parameter Names
        path: ./pages/extensions/parameter-names.mdx
      - page: Other
        path: ./pages/extensions/others.mdx
        slug: others
  - page: Overlay Customizations
    path: ./pages/overrides.mdx
  - page: Sync your OpenAPI Specification
    path: ./pages/automation.mdx            
  - section: Integrate your Server Framework
    slug: frameworks
    contents:
      - page: FastAPI
        icon: fa-regular fa-circle-bolt
        path: ./pages/server-frameworks/fastapi.mdx
        slug: fastapi
