name: Preview Docs

on:
  pull_request_target:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Only for commenting
      contents: read # For checking out code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          git checkout pr-${{ github.event.pull_request.number }}

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate preview URL
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          OUTPUT=$(fern generate --docs --preview --instance fern-api.docs.buildwithfern.com/learn 2>&1) || true
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
          echo "Preview URL: $URL"
          echo "🌿 Preview your docs: $URL" > preview_url.txt

      - name: Comment URL in PR
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          filePath: preview_url.txt
