name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: | 
          fern generate --docs --instance fern-api.docs.buildwithfern.com/learn
          fern generate --docs --instance fern-v2.docs.buildwithfern.com/learn/v2
